# Generated by Django 3.0.5 on 2020-04-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Product',
        ),
    ]
