# Generated by Django 3.0.5 on 2020-04-25 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200408_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
