# Generated by Django 3.0.5 on 2020-04-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200426_1912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='category',
        ),
    ]
