# Generated by Django 3.0.5 on 2020-04-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200426_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
