# Generated by Django 3.0.5 on 2020-04-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200428_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
