# Generated by Django 3.0.5 on 2020-05-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200506_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Not in Stock', 'Not in Stock')], max_length=200, null=True),
        ),
    ]
